steps:
# build image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t=gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'
  - '--build-arg=short_sha=$SHORT_SHA'
  - '--build-arg=branch_name=$BRANCH_NAME'
  - '.'

# push the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA']

# publish
- name: 'ubuntu'
  args: ['echo', '$TAG_NAME', '$BRANCH_NAME']

images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA']